name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      RAILS_ENV: test
      CLERK_SECRET_KEY: "sk_test_mock_key_for_ci"
      CLERK_PUBLISHABLE_KEY: "pk_test_mock_key_for_ci"
      BILLETTO_ACCESS_KEY_ID: "ac_test_mock_key_for_ci"
      BILLETTO_ACCESS_KEY_SECRET: "acs_test_mock_key_for_ci"

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Set up database schema
        env:
          RAILS_ENV: test
          DATABASE_URL: "mysql2://root@127.0.0.1:3306/billetto_rails_test"
        run: bundle exec rails db:test:prepare

      # Replaces the default Minitest runner commands with RSpec
      - name: Run RSpec tests
        env:
          RAILS_ENV: test
          DATABASE_URL: "mysql2://root@127.0.0.1:3306/billetto_rails_test"
          CLERK_SECRET_KEY: "sk_test_mock_key_for_ci"
          CLERK_PUBLISHABLE_KEY: "pk_test_mock_key_for_ci"
          BILLETTO_ACCESS_KEY_ID: "ac_test_mock_key_for_ci"
          BILLETTO_ACCESS_KEY_SECRET: "acs_test_mock_key_for_ci"
        run: bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
